version: "3"
services:
  mysql_db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=licenta
      - MYSQL_PASSWORD=root
    networks:
      - project_network
    ports:
      - 3306:3306
    container_name: mysql_db

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - project_network
    container_name: mongo

  backend:
    build: back-end
    networks:
      - project_network
    depends_on:
      #- rabbitmq
      - mysql_db
      - mongo
    ports:
      - 8080:8080
    container_name: backend

  frontend:
    build: front-end
    networks:
      - project_network
    depends_on:
      - backend
    ports:
      - 80:80
    links: 
      - backend
    container_name: frontend
  
networks:
  project_network:
    driver: bridge

